### ISSUE TITLE
Cursor bug!?

### ISSUE THREAD

**Issue by lamnguyenvux** [yeyushengfan258/Miya-kde#1]
When I move the cursor to the desktop or place it on the taskbar, the cursor changes from the white one to the black one. I try to reboot few times but the problem is the same. Let me know if it's an actual bug or something is wrong with my os.

![IMG_20220304_2320537~2.jpg](https://user-images.githubusercontent.com/83378878/156813911-2017cc96-e265-47a1-a757-e307d34dc178.jpg)

![IMG_20220304_2320365~2.jpg](https://user-images.githubusercontent.com/83378878/156813931-6c862724-e785-4666-af90-b4c26d86186e.jpg)

**Comment by yeyushengfan258** [comment]
As far as I can tell, this is an issue with the KDE desktop, not the theme. 
Sorry, this is not something I can solve, I will only wait for a later version update to see if it will be solved.

**Comment by lamnguyenvux** [comment]
I think I'll live with it for a while. I really like this theme.

**Comment by lamnguyenvux** [comment]
I have fixed it. Definitely this issue was from KDE. I changed a line: Inherits=xcursors_breeze to Inherits=Afterglow-cursors in /usr/share/icons/default/index.theme :D

**Comment by yeyushengfan258** [comment]
Great, I even learned something from you.
Thank you.
